apiVersion: v1
kind: Service
metadata:
  name: exam-deployment2
  labels:
    app: test
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
