apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment2
  labels:
    app: test
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec: 
      containers:
      - image: ironheart81/exam:latest
        name: hello-exam
        ports: 
          - containerPort: 8080