apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment2
  labels:
    app: test
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec: 
      containers:
      - image: ironheart81/exam:latest
        name: hello-exam
        ports: 
          - containerPort: 8080
        volumeMounts:
          - name: myvolume
            mountPath: /data
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: exam-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: exam-deployment2
  labels:
    app: test
spec:
  selector:
    app: test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exam-pvc
  labels:
    app: test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


 
    


